# Generated by Django 5.2.11 on 2026-02-19 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Visitor's IP address.", null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Raw HTTP User-Agent string.')),
                ('referrer', models.TextField(blank=True, default='', help_text='HTTP Referer header — where the click originated from.')),
                ('country', models.CharField(blank=True, db_index=True, default='', help_text='Country name from IP geolocation.', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 country code (e.g. 'US', 'IN', 'GB').", max_length=5)),
                ('city', models.CharField(blank=True, default='', help_text='City from IP geolocation.', max_length=100)),
                ('region', models.CharField(blank=True, default='', help_text='State/province from IP geolocation.', max_length=100)),
                ('device_type', models.CharField(blank=True, db_index=True, default='unknown', help_text='mobile / tablet / desktop / bot / unknown', max_length=20)),
                ('browser', models.CharField(blank=True, db_index=True, default='', help_text='Browser name (e.g. Chrome, Firefox, Safari).', max_length=100)),
                ('browser_version', models.CharField(blank=True, default='', help_text='Browser version string.', max_length=50)),
                ('os', models.CharField(blank=True, db_index=True, default='', help_text='Operating system name (e.g. Windows, macOS, Android, iOS).', max_length=100)),
                ('os_version', models.CharField(blank=True, default='', help_text='OS version string.', max_length=50)),
                ('is_unique', models.BooleanField(db_index=True, default=False, help_text='True = first time this IP has clicked this specific short URL.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact timestamp of the click event.')),
            ],
            options={
                'verbose_name': 'Click',
                'verbose_name_plural': 'Clicks',
                'db_table': 'clicks',
                'ordering': ['-created_at'],
            },
        ),
    ]
