# Generated by Django 5.2.11 on 2026-02-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='short_url',
            field=models.ForeignKey(help_text='The short URL that was clicked.', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='urls.shorturl'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['short_url', '-created_at'], name='clicks_short_u_a71fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['short_url', 'ip_address'], name='clicks_short_u_0c5d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['short_url', 'is_unique'], name='clicks_short_u_40b7cf_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['short_url', 'device_type'], name='clicks_short_u_4119ce_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['short_url', 'country'], name='clicks_short_u_ea68d4_idx'),
        ),
        migrations.AddIndex(
            model_name='click',
            index=models.Index(fields=['created_at'], name='clicks_created_51fa28_idx'),
        ),
    ]
