# Generated by Django 5.2.11 on 2026-02-19 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of this short URL. Null = anonymous link.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['slug'], name='short_urls_slug_87d374_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['user', '-created_at'], name='short_urls_user_id_145413_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['is_active', 'is_flagged'], name='short_urls_is_acti_b532dc_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['expires_at'], name='short_urls_expires_08c820_idx'),
        ),
    ]
