# Generated by Django 5.2.11 on 2026-02-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='qr_enabled',
            field=models.BooleanField(default=False, help_text='When True, a QR code can be generated on-the-fly for this link via /qr/<slug>.'),
        ),
    ]
