# Generated by Django 5.2.11 on 2026-02-19 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.TextField(help_text='The full long URL this short link redirects to.')),
                ('slug', models.CharField(db_index=True, help_text="The short identifier (e.g. 'abc123'). Must be unique across all users.", max_length=50, unique=True)),
                ('title', models.CharField(blank=True, default='', help_text='Optional human-readable label for the link.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes or description for this link.')),
                ('is_active', models.BooleanField(default=True, help_text='When False, the link is disabled and redirects will be blocked.')),
                ('is_flagged', models.BooleanField(db_index=True, default=False, help_text='True = link was detected as unsafe or reported by admin.')),
                ('flag_reason', models.CharField(blank=True, default='', help_text="Reason for flagging (e.g. 'MALWARE', 'PHISHING', 'ADMIN_REVIEW').", max_length=255)),
                ('is_private', models.BooleanField(default=False, help_text='When True, redirect requires a password.')),
                ('password_hash', models.CharField(blank=True, default='', help_text='bcrypt hash of the URL password. Only set when is_private=True.', max_length=255)),
                ('is_single_use', models.BooleanField(default=False, help_text='When True, the link can only be clicked once.')),
                ('token', models.CharField(blank=True, db_index=True, default='', help_text='Secret token for single-use or token-gated access.', max_length=128)),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp of when a single-use link was accessed.', null=True)),
                ('max_clicks', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this link can be clicked. Null = unlimited.', null=True)),
                ('click_count', models.PositiveIntegerField(default=0, help_text='Denormalized total click counter. Updated atomically on each click.')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='After this datetime, the link redirects to the expiry page. Null = no expiry.', null=True)),
                ('activates_at', models.DateTimeField(blank=True, help_text='Before this datetime, the link is not yet available. Null = active immediately.', null=True)),
                ('redirect_rules', models.JSONField(blank=True, default=list, help_text="JSON array of conditional redirect rules. Rules are evaluated in order; first match wins. Example: [{'condition': 'device=mobile', 'target_url': 'https://m.example.com'}, {'condition': 'country=US', 'target_url': 'https://us.example.com'}]")),
                ('webhook_url', models.URLField(blank=True, default='', help_text='When set, a POST request is fired to this URL on every click.')),
                ('qr_code', models.CharField(blank=True, default='', help_text='File path to the generated QR code image (relative to MEDIA_ROOT).', max_length=255)),
                ('is_url_reachable', models.BooleanField(blank=True, help_text='Result of the most recent HTTP reachability check. Null = not yet checked.', null=True)),
                ('url_status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code from the most recent reachability check (e.g. 200, 404, 301).', null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='When the URL health was last verified.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Short URL',
                'verbose_name_plural': 'Short URLs',
                'db_table': 'short_urls',
                'ordering': ['-created_at'],
            },
        ),
    ]
