# Generated by Django 5.2.11 on 2026-02-22 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tunnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias', models.SlugField(help_text="Public alias (e.g. 'my-app'). Unique across all users.", max_length=30, unique=True)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw tunnel token. Raw token is never stored.', max_length=64)),
                ('local_port', models.PositiveIntegerField(blank=True, help_text='The local port the agent forwards to. Stored for display only.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='When False, the tunnel is disabled and connections are rejected.')),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('error', 'Error')], db_index=True, default='disconnected', help_text='Live connection state updated by the WebSocket consumer.', max_length=16)),
                ('last_connected_at', models.DateTimeField(blank=True, help_text='When the agent last successfully connected.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this tunnel.', on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tunnel',
                'verbose_name_plural': 'Tunnels',
                'db_table': 'tunnels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alias'], name='tunnels_alias_374e51_idx'), models.Index(fields=['user', '-created_at'], name='tunnels_user_id_c3eadd_idx'), models.Index(fields=['is_active', 'status'], name='tunnels_is_acti_97b717_idx')],
            },
        ),
    ]
