# Generated by Django 5.2.11 on 2026-02-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunnels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tunnel',
            name='bandwidth_bytes',
            field=models.BigIntegerField(default=0, help_text='Total data transferred through this tunnel in bytes.'),
        ),
    ]
