# Generated by Django 5.2.11 on 2026-02-19 15:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID).', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Primary login identifier. Must be unique.', max_length=254, unique=True)),
                ('username', models.CharField(db_index=True, help_text='Public display name. Must be unique.', max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=False, help_text='Admin users have access to the admin dashboard and elevated permissions.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive users cannot log in. Use this instead of deleting accounts.')),
                ('is_verified', models.BooleanField(default=False, help_text='Email verification status. Verified users have full access.')),
                ('is_staff', models.BooleanField(default=False, help_text='Required by Django admin interface.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw refresh token.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='When this refresh token expires.')),
                ('is_revoked', models.BooleanField(default=False, help_text='True = token has been revoked (user logged out).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'refresh_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='refresh_tok_token_h_2fa7c6_idx'), models.Index(fields=['user', 'is_revoked'], name='refresh_tok_user_id_893d6c_idx')],
            },
        ),
    ]
